version: "2"
services:
  web:
    build: ./webapp
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
